// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finaz_app.Server.Models;

#nullable disable

namespace finaz_app.Server.Migrations
{
    [DbContext(typeof(FinanzAppContext))]
    [Migration("20241204065637_AddFotoPerfilToUsuarios")]
    partial class AddFotoPerfilToUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("finaz_app.Server.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateTime?>("FechaModificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("isSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("CategoriaId")
                        .HasName("CAT_CategoriaID_PK");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("finaz_app.Server.Models.Gasto", b =>
                {
                    b.Property<int>("GastoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GastoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GastoId"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateTime?>("FechaModificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("GastoId")
                        .HasName("GST_GastoID_PK");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("finaz_app.Server.Models.Ingreso", b =>
                {
                    b.Property<int>("IngresoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IngresoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngresoId"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("CategoriaID");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<DateTime?>("FechaModificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(CONVERT([date],getdate()))");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IngresoId")
                        .HasName("ING_IngresoID_PK");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("finaz_app.Server.Models.MetaAhorro", b =>
                {
                    b.Property<int>("MetaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MetaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetaId"));

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(GETDATE())");

                    b.Property<DateTime>("FechaMeta")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaModificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(GETDATE())");

                    b.Property<int?>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoAhorrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("MontoObjetivo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("isDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("MetaId")
                        .HasName("MA_MetaId_PK");

                    b.HasIndex("CreadoPor");

                    b.HasIndex("ModificadoPor");

                    b.ToTable("MetasAhorro", t =>
                        {
                            t.HasCheckConstraint("CHK_MontoAhorrado", "[MontoAhorrado] <= [MontoObjetivo]");
                        });
                });

            modelBuilder.Entity("finaz_app.Server.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("usuario");

                    b.HasKey("UsuarioId")
                        .HasName("USR_UsuarioID_PK");

                    b.HasIndex(new[] { "CorreoElectronico" }, "UQ__Usuarios__60695A19A3DBD5FB")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("finaz_app.Server.Models.Categoria", b =>
                {
                    b.HasOne("finaz_app.Server.Models.Usuario", "CreadoPorNavigation")
                        .WithMany("CategoriaCreadoPorNavigations")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CAT_USR_CreadoPor_FK");

                    b.HasOne("finaz_app.Server.Models.Usuario", "ModificadoPorNavigation")
                        .WithMany("CategoriaModificadoPorNavigations")
                        .HasForeignKey("ModificadoPor")
                        .HasConstraintName("CAT_USR_ModificadoPor_FK");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("ModificadoPorNavigation");
                });

            modelBuilder.Entity("finaz_app.Server.Models.Gasto", b =>
                {
                    b.HasOne("finaz_app.Server.Models.Categoria", "Categoria")
                        .WithMany("Gastos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("GST_CAT_CategoriaID_FK");

                    b.HasOne("finaz_app.Server.Models.Usuario", "CreadoPorNavigation")
                        .WithMany("GastoCreadoPorNavigations")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("GST_USR_CreadoPor_FK");

                    b.HasOne("finaz_app.Server.Models.Usuario", "ModificadoPorNavigation")
                        .WithMany("GastoModificadoPorNavigations")
                        .HasForeignKey("ModificadoPor")
                        .HasConstraintName("GTS_USR_ModificadoPor_FK");

                    b.Navigation("Categoria");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("ModificadoPorNavigation");
                });

            modelBuilder.Entity("finaz_app.Server.Models.Ingreso", b =>
                {
                    b.HasOne("finaz_app.Server.Models.Categoria", "Categoria")
                        .WithMany("Ingresos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("ING_CAT_CategoriaID_FK");

                    b.HasOne("finaz_app.Server.Models.Usuario", "CreadoPorNavigation")
                        .WithMany("IngresoCreadoPorNavigations")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ING_USR_CreadoPor_FK");

                    b.HasOne("finaz_app.Server.Models.Usuario", "ModificadoPorNavigation")
                        .WithMany("IngresoModificadoPorNavigations")
                        .HasForeignKey("ModificadoPor")
                        .HasConstraintName("ING_USR_ModificadoPor_FK");

                    b.Navigation("Categoria");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("ModificadoPorNavigation");
                });

            modelBuilder.Entity("finaz_app.Server.Models.MetaAhorro", b =>
                {
                    b.HasOne("finaz_app.Server.Models.Usuario", "CreadoPorNavigation")
                        .WithMany("MetaAhorroCreadoPorNavigations")
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("MA_USR_CreadoPor_FK");

                    b.HasOne("finaz_app.Server.Models.Usuario", "ModificadoPorNavigation")
                        .WithMany("MetaAhorroModificadoPorNavigations")
                        .HasForeignKey("ModificadoPor")
                        .HasConstraintName("MA_USR_ModificadoPor_FK");

                    b.Navigation("CreadoPorNavigation");

                    b.Navigation("ModificadoPorNavigation");
                });

            modelBuilder.Entity("finaz_app.Server.Models.Categoria", b =>
                {
                    b.Navigation("Gastos");

                    b.Navigation("Ingresos");
                });

            modelBuilder.Entity("finaz_app.Server.Models.Usuario", b =>
                {
                    b.Navigation("CategoriaCreadoPorNavigations");

                    b.Navigation("CategoriaModificadoPorNavigations");

                    b.Navigation("GastoCreadoPorNavigations");

                    b.Navigation("GastoModificadoPorNavigations");

                    b.Navigation("IngresoCreadoPorNavigations");

                    b.Navigation("IngresoModificadoPorNavigations");

                    b.Navigation("MetaAhorroCreadoPorNavigations");

                    b.Navigation("MetaAhorroModificadoPorNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
