name: CI Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore .NET dependencies
        run: dotnet restore ./finaz-app.Server/finaz-app.Server.csproj

      - name: Create HTTPS Development Certificate
        run: |
          mkdir -p $HOME/.aspnet/https
          dotnet dev-certs https --trust --export-path "$HOME/.aspnet/https/finaz-app.client.pem" --format Pem --no-password

      - name: Build .NET project
        run: dotnet build ./finaz-app.Server/finaz-app.Server.csproj --configuration Release

      - name: Run .NET tests
        run: dotnet test ./finaz-app.Tests/finaz-app.Tests.csproj --configuration Release

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd finaz-app.client
          npm install

      - name: Run frontend tests
        run: |
          cd finaz-app.client
          npm test

      - name: Build frontend
        run: |
          cd finaz-app.client
          npm run build

      - name: Run Cypress tests
        run: |
          cd finaz-app.client
          npm run cypress:run
